version: '3.9'

services:
  backend:
    build: ./backend
    container_name: sapi_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: sapi_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  db:
    image: postgis/postgis:15-3.3
    container_name: sapi_postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: satdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: sapi_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
